version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: library
            DB_PORT: 5432
            DB_SSLMODE: disable
            REDIS_HOST: redis
            REDIS_PORT: 6379
        networks:
            - shared_network
        restart: on-failure

    db:
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: library
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - shared_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - shared_network
        restart: on-failure
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5

volumes:
    pgdata:

networks:
    shared_network:
        driver: bridge
